# Generated by Django 5.2.6 on 2025-09-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rev_doctor__b0eee6_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rev_patient_e031c2_idx',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
