# Generated by Django 5.2.6 on 2025-09-14 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_timeslot_date_appointment'),
        ('doctors', '0002_alter_specialty_options_alter_doctor_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='doctors.doctor'),
        ),
    ]
