# Generated by Django 5.2.6 on 2025-09-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['name'], 'verbose_name': 'Specialty', 'verbose_name_plural': 'Specialties'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='description',
            field=models.TextField(help_text='Detailed description of the specialty'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(help_text='Name of the medical specialty (e.g., Cardiology, Neurology)', max_length=255, unique=True),
        ),
    ]
